
---
kind: ImageStream
apiVersion: v1
metadata:
  name: book-service
status:
  dockerImageRepository: ''

---
kind: BuildConfig
apiVersion: v1
metadata:
  name: book-service-build
  labels:
    name: book-service-build
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  source:
    type: Git
    git:
      uri: https://github.com/lukeelten/openshift-book-service.git

  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: heinlein
        name: php:latest

  output:
    to:
      kind: ImageStreamTag
      name: book-service:latest

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-config
data:
  proxy.json: |
    {
      "target-url":"http://localhost:8080",
      "bind-address":"0.0.0.0",
      "http-port":"8000",
      "send-access-token": true,
      "applications": [
      {
        "base-path":"/",
        "proxy-address-forwarding": true,
        "adapter-config":{
          "realm":"heinlein",
          "auth-server-url":"https://keycloak-heinlein.apps.cc-openshift.de/auth",
          "ssl-required":"external",
          "resource":"book-service",
          "credentials":{
            "secret":"c5787db3-f875-4a12-8765-66e8d4ea6fcb"
          }
        },
        "constraints": [
        {
          "pattern":"/*",
          "authenticate": true
        },
        {
          "pattern":"/",
          "authenticate": true
        }
        ]
      }
      ],
      "header-names": {
        "keycloak-access-token": "X-KEYCLOAK-TOKEN"
      }
    }



---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: "book-service"
  annotations:
    description: Deploy latest book service image
    template.alpha.openshift.io/wait-for-ready: 'true'

spec:
  strategy:
    type: Recreate

  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - book-service
      from:
        kind: ImageStreamTag
        namespace: heinlein
        name: "book-service:latest"
  - type: ConfigChange

  replicas: 1
  selector:
    name: "book-service"

  template:
    metadata:
      name: "book-service"
      labels:
        name: "book-service"

    spec:
      containers:
      - name: book-service
        image: " "
        ports:
        - containerPort: 8080

      - name: book-service-sidecar
        image: jboss/keycloak-proxy
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /opt/jboss/conf
          name: proxy-config-volume

      volumes:
      - name: proxy-config-volume
        configMap:
          name: proxy-config
          items:
          - key: proxy.json
            path: proxy.json

---
kind: Service
apiVersion: v1
metadata:
  name: book-service
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    name: book-service

---
kind: Route
apiVersion: v1
metadata:
  name: book-service-route
spec:
  to:
    kind: Service
    name: book-service