version: '2'

volumes:
  postgres_keycloak:
    driver: local

networks:
  keycloak-network:
    driver: bridge

services:
  postgres-keycloak:
    image: postgres:alpine
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - keycloak-network

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    expose:
      - 8080
      - 8443
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres-keycloak
    networks:
      - keycloak-network