version: '3'

volumes:
  postgres_keycloak:
    driver: local
  postgres_kong:
    driver: local


services:
  postgres-keycloak:
    image: postgres:alpine
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres-keycloak


  postgres-kong:
    image: postgres:alpine
    volumes:
      - postgres_kong:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_DATABASE: kong
      KONG_CASSANDRA_CONTACT_POINTS: postgres-kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - postgres-kong
      - kong-migration

  kong-migration:
    image: kong:latest
    depends_on:
      - postgres-kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
    command: kong migrations up



  backend:
    image: nginx:alpine
    volumes:
      - ./backend:/app
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - 8880:8080
    depends_on:
      - php

  php:
    image: php:fpm-alpine
    volumes:
      - ./backend:/app

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/app
    ports:
      - 8881:80