version: '3'

volumes:
  postgres_kong:
    driver: local


services:

  postgres-kong:
    image: postgres:alpine
    volumes:
      - postgres_kong:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
      KONG_PG_DATABASE: kong
      KONG_CASSANDRA_CONTACT_POINTS: postgres-kong
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - postgres-kong
      - kong-migration

  kong-migration:
    image: kong:latest
    depends_on:
      - postgres-kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgres-kong
    command: kong migrations up

  rest:
    image: lukeelten/simple-rest
    ports:
      - 9090:8080